title: TrinityShield Documentation
description: Official documentation for TrinityShield.

# GitHub Pages config
baseurl: "/TrinityShield"
url: "https://trinity963.github.io"

markdown: kramdown
kramdown:
  input: GFM

# Include all docs assets
include:
  - docs
  - docs/assets
  - docs/css
  - docs/js
  - docs/_data
  - docs/_includes
  - docs/_layouts

exclude:
  - "*.sh"
  - "*.bat"
  - "node_modules"
  - "package.json"
  - "package-lock.json"

# Where Jekyll reads documents from
collections:
  pages:
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
