theme: minima
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - node_modules
  - devkit
  - scripts

include:
  - _layouts
  - _includes

defaults:
  - scope:
      path: ""
    values:
      layout: default
